# Generated by Django 4.0.5 on 2022-07-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='Coach',
            new_name='Administrador',
        ),
        migrations.DeleteModel(
            name='Atleta',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
